const fs = require('fs');

const langs = ['en', 'de', 'pt', 'lb'];
const files = {};
for (const lang of langs) {
  const path = `C:/tevaxia/src/messages/${lang}.json`;
  files[lang] = JSON.parse(fs.readFileSync(path, 'utf8'));
}

// ========== 2. outilsBancaires.seo ==========
files.en.outilsBancaires.seo = {
  "faqTitle": "Frequently asked questions about mortgage lending in Luxembourg",
  "relatedTitle": "Related tools",
  "creditTitle": "Mortgage lending tools for Luxembourg",
  "creditContent": "<p>The Luxembourg mortgage market has significant specificities compared to neighbouring countries. The banking sector is dominated by local players (Spuerkeess/BCEE, BIL, BGL BNP Paribas, Raiffeisen) and international banks (ING, Deutsche Bank) offering differentiated terms.</p><p>Interest rates in Luxembourg follow the <strong>European Central Bank (ECB)</strong> decisions, with a typical bank spread of 80 to 150 basis points above the refinancing rate. In 2025, 10-year fixed rates stand around 3.0 to 3.8%, while variable rates (indexed to 3-month EURIBOR) range from 3.2 to 4.0%.</p><p>The <strong>CSSF</strong> (Commission de Surveillance du Secteur Financier) regulates lending practices through its circulars and recommendations, notably regarding LTV (Loan-to-Value) ratios and repayment capacity. Since 2020, the Systemic Risk Committee (CRS) has issued macro-prudential recommendations specific to the Luxembourg market.</p>",
  "ltvTitle": "LTV ratio and CSSF thresholds",
  "ltvContent": "<p>The <strong>Loan-to-Value (LTV) ratio</strong> is the ratio between the loan amount and the property value. The CSSF and CRS have issued differentiated LTV cap recommendations:</p><ul><li><strong>First-time buyers (primary residence)</strong>: recommended maximum LTV of 100% (full financing possible under conditions). In practice, banks frequently grant LTVs of 90 to 100% to first-time buyers benefiting from the State guarantee.</li><li><strong>Non-first-time buyers (primary residence)</strong>: recommended maximum LTV of 90%, i.e. a 10% deposit.</li><li><strong>Buy-to-let investment</strong>: LTV capped at 80%, requiring a minimum 20% deposit. Some banks are more restrictive (75%).</li><li><strong>Buy-to-let</strong>: specific conditions apply, sometimes with 70% LTV thresholds and rate premiums of 20 to 50 bps.</li></ul><p>Importantly, the LTV is calculated on the <strong>appraised value</strong> of the property, not the purchase price. If the purchase price exceeds the appraisal, the bank will use the lower value.</p>",
  "capaciteTitle": "Borrowing capacity and the 40% rule",
  "capaciteContent": "<p>Borrowing capacity is determined by the <strong>debt-to-income ratio</strong>, which should generally not exceed <strong>40% of net household income</strong> in Luxembourg. This threshold is more generous than in some neighbouring countries (35% in France, 33% in Belgium).</p><ul><li><strong>Income considered</strong>: net salary, rental income (generally retained at 70-80%), self-employment income (3-year average), pensions.</li><li><strong>Deducted charges</strong>: existing loans, alimony, residual rent if applicable.</li><li><strong>Residual income</strong>: beyond the debt ratio, Luxembourg banks verify a minimum residual income threshold (approximately EUR 1,200/month for a single person, EUR 2,000 for a couple).</li></ul><p>Our simulator calculates the maximum admissible monthly payment and derives the maximum borrowable amount based on the chosen duration and rate.</p>",
  "amortissementTitle": "Repayment: constant vs progressive",
  "amortissementContent": "<p>Luxembourg banks mainly offer two types of repayment schedules:</p><ul><li><strong>Constant repayment (fixed annuities)</strong>: the monthly payment remains fixed throughout the loan term. The interest portion decreases progressively while the principal portion increases. This is the most common scheme in Luxembourg.</li><li><strong>Linear repayment (constant principal)</strong>: the principal repayment is identical each month, producing decreasing monthly payments. Interest decreases regularly. This scheme is more advantageous in total interest cost but requires higher initial payments.</li><li><strong>Bullet (interest-only)</strong>: only interest is paid during the loan term, with principal repaid in full at maturity. Used mainly for buy-to-let investments with a life insurance policy as collateral.</li></ul><p>Our amortisation table details month-by-month the evolution of outstanding principal, the interest/principal split and the total credit cost.</p>",
  "dscrTitle": "DSCR for buy-to-let investment",
  "dscrContent": "<p>The <strong>Debt Service Coverage Ratio (DSCR)</strong> is a ratio used by banks to assess a rental property's ability to cover debt service:</p><p><strong>DSCR = Net Operating Income / Annual Debt Service</strong></p><ul><li>A DSCR above <strong>1.20</strong> is generally required by Luxembourg banks for a buy-to-let mortgage.</li><li>A DSCR of <strong>1.00</strong> means that rents exactly cover repayments \u2014 a risky situation in case of vacancy or unforeseen events.</li><li>A DSCR below <strong>1.00</strong> means the investor must supplement debt service from personal income.</li></ul><p>For the calculation, net income includes a normative vacancy allowance (generally 5 to 8%), non-recoverable charges and a maintenance provision. Debt service includes both interest and principal repayment.</p>",
  "faq1Q": "Fixed or variable rate: which to choose in Luxembourg?",
  "faq1A": "The choice depends on your risk profile and time horizon. A fixed rate offers the security of a constant monthly payment, recommended if you are borrowing at maximum capacity. A variable rate (EURIBOR + margin) can be more advantageous if rates fall, but exposes you to increases. In Luxembourg, a popular option is the capped variable rate, combining a variable rate with a ceiling. In 2025, the gap between fixed and variable has narrowed, making fixed rates particularly attractive.",
  "faq2Q": "What is the minimum deposit to buy in Luxembourg?",
  "faq2A": "For first-time buyers (primary residence), 100% financing is theoretically possible thanks to the State guarantee. In practice, banks recommend a deposit of 10 to 20%. For buy-to-let investment, the minimum deposit is 20% (80% LTV). Acquisition costs (registration duties, notary fees, VAT) represent approximately 7 to 10% of the price and are generally not financed \u2014 they must be added to the deposit.",
  "faq3Q": "How does the Luxembourg State guarantee work?",
  "faq3A": "The State housing guarantee (amended law of 25 February 1979) allows first-time buyers to benefit from a public guarantee covering up to 30% of the loan amount, capped at EUR 250,000. This guarantee facilitates obtaining a loan without a personal deposit. Conditions include a household income ceiling and the obligation to occupy the property as a primary residence. Applications are made to the Ministry of Housing via the myguichet.lu portal.",
  "faq4Q": "What is the impact of CPE energy class on the mortgage?",
  "faq4A": "Following CSSF recommendations on climate risks, Luxembourg banks are progressively integrating energy performance into their lending criteria. A property rated A-B may benefit from preferential conditions (rate reduction of 10 to 30 bps). Conversely, properties rated F-G (energy sieves) undergo enhanced analysis, sometimes with an appraisal discount and provisioning for energy renovation costs.",
  "faq5Q": "Can I refinance a mortgage in Luxembourg?",
  "faq5A": "Yes, refinancing is possible and can be advantageous if rates have fallen since origination. Costs to anticipate include: the early repayment indemnity (IRA, capped at 6 months' interest or 1% of repaid capital under the Consumer Code), mortgage release fees (approximately EUR 500 to 1,000), and new mortgage registration fees. The profitability calculation depends on the rate differential, outstanding capital and residual duration."
};

files.de.outilsBancaires.seo = {
  "faqTitle": "H\u00e4ufig gestellte Fragen zum Immobilienkredit in Luxemburg",
  "relatedTitle": "Erg\u00e4nzende Tools",
  "creditTitle": "Immobilienkredit-Tools f\u00fcr Luxemburg",
  "creditContent": "<p>Der luxemburgische Immobilienkreditmarkt weist im Vergleich zu den Nachbarl\u00e4ndern bedeutende Besonderheiten auf. Der Bankensektor wird von lokalen Akteuren (Spuerkeess/BCEE, BIL, BGL BNP Paribas, Raiffeisen) und internationalen Banken (ING, Deutsche Bank) dominiert, die unterschiedliche Konditionen anbieten.</p><p>Die Zinss\u00e4tze in Luxemburg folgen den Entscheidungen der <strong>Europ\u00e4ischen Zentralbank (EZB)</strong>, mit einem typischen Bankenspread von 80 bis 150 Basispunkten \u00fcber dem Refinanzierungssatz. Im Jahr 2025 liegen die 10-j\u00e4hrigen Festzinsen bei etwa 3,0 bis 3,8 %, w\u00e4hrend variable Zinsen (indexiert auf den 3-Monats-EURIBOR) zwischen 3,2 und 4,0 % schwanken.</p><p>Die <strong>CSSF</strong> reguliert die Vergabepraxis \u00fcber ihre Rundschreiben und Empfehlungen, insbesondere hinsichtlich des LTV-Verh\u00e4ltnisses (Loan-to-Value) und der R\u00fcckzahlungsf\u00e4higkeit. Seit 2020 hat der Ausschuss f\u00fcr Systemrisiken (CRS) spezifische makroprudenzielle Empfehlungen f\u00fcr den luxemburgischen Markt herausgegeben.</p>",
  "ltvTitle": "LTV-Verh\u00e4ltnis und CSSF-Schwellenwerte",
  "ltvContent": "<p>Das <strong>Loan-to-Value-Verh\u00e4ltnis (LTV)</strong> ist das Verh\u00e4ltnis zwischen Darlehensbetrag und Immobilienwert. CSSF und CRS haben differenzierte LTV-Obergrenzen empfohlen:</p><ul><li><strong>Erstk\u00e4ufer (Hauptwohnsitz)</strong>: empfohlener maximaler LTV von 100 % (Vollfinanzierung unter Bedingungen m\u00f6glich). In der Praxis gew\u00e4hren Banken Erstk\u00e4ufern mit Staatsgarantie h\u00e4ufig LTVs von 90 bis 100 %.</li><li><strong>Nicht-Erstk\u00e4ufer (Hauptwohnsitz)</strong>: empfohlener maximaler LTV von 90 %, also 10 % Eigenkapital.</li><li><strong>Kapitalanlage</strong>: LTV begrenzt auf 80 %, mindestens 20 % Eigenkapital erforderlich. Einige Banken sind restriktiver (75 %).</li><li><strong>Buy-to-let</strong>: besondere Bedingungen gelten, teilweise mit 70 % LTV-Schwellen und Zinsaufschl\u00e4gen von 20 bis 50 Bps.</li></ul><p>Wichtig: Der LTV wird auf Basis des <strong>Sch\u00e4tzwerts</strong> der Immobilie berechnet, nicht des Kaufpreises. \u00dcbersteigt der Kaufpreis den Sch\u00e4tzwert, verwendet die Bank den niedrigeren Wert.</p>",
  "capaciteTitle": "Kreditkapazit\u00e4t und die 40-%-Regel",
  "capaciteContent": "<p>Die Kreditkapazit\u00e4t wird durch die <strong>Schuldendienstquote</strong> bestimmt, die in Luxemburg in der Regel <strong>40 % des Nettoeinkommens</strong> des Haushalts nicht \u00fcberschreiten sollte. Dieser Schwellenwert ist gro\u00dfz\u00fcgiger als in einigen Nachbarl\u00e4ndern (35 % in Frankreich, 33 % in Belgien).</p><ul><li><strong>Ber\u00fccksichtigte Einkommen</strong>: Nettogehalt, Mieteinnahmen (in der Regel zu 70-80 % angerechnet), Einkommen aus selbstst\u00e4ndiger T\u00e4tigkeit (3-Jahres-Durchschnitt), Renten.</li><li><strong>Abgezogene Belastungen</strong>: laufende Kredite, Unterhaltszahlungen, verbleibende Miete falls zutreffend.</li><li><strong>Verbleibendes Einkommen</strong>: \u00dcber die Schuldenquote hinaus pr\u00fcfen luxemburgische Banken ein Mindest-Resteinkommen (ca. 1.200 EUR/Monat f\u00fcr Alleinstehende, 2.000 EUR f\u00fcr Paare).</li></ul><p>Unser Simulator berechnet die maximal zul\u00e4ssige Monatsrate und leitet daraus den maximalen Kreditbetrag ab.</p>",
  "amortissementTitle": "Tilgung: konstant vs. progressiv",
  "amortissementContent": "<p>Luxemburgische Banken bieten haupts\u00e4chlich zwei Tilgungsarten an:</p><ul><li><strong>Konstante Tilgung (feste Annuit\u00e4ten)</strong>: Die Monatsrate bleibt w\u00e4hrend der gesamten Laufzeit gleich. Der Zinsanteil sinkt progressiv, w\u00e4hrend der Tilgungsanteil steigt. Dies ist das g\u00e4ngigste Modell in Luxemburg.</li><li><strong>Lineare Tilgung (konstanter Kapitalbetrag)</strong>: Die Kapitalr\u00fcckzahlung ist jeden Monat gleich, was zu sinkenden Monatsraten f\u00fchrt. Die Zinsen sinken regelm\u00e4\u00dfig. Dieses Modell ist bei den Gesamtzinskosten vorteilhafter, erfordert aber h\u00f6here Anfangsraten.</li><li><strong>Endf\u00e4llig (tilgungsfrei)</strong>: W\u00e4hrend der Laufzeit werden nur Zinsen gezahlt, das Kapital wird am Ende in einer Summe zur\u00fcckgezahlt. Wird haupts\u00e4chlich bei Kapitalanlagen mit einer Lebensversicherung als Sicherheit eingesetzt.</li></ul><p>Unser Tilgungsplan zeigt Monat f\u00fcr Monat die Entwicklung der Restschuld, die Aufteilung Zinsen/Tilgung und die Gesamtkosten des Kredits.</p>",
  "dscrTitle": "DSCR f\u00fcr Kapitalanlageimmobilien",
  "dscrContent": "<p>Die <strong>Debt Service Coverage Ratio (DSCR)</strong> ist eine Kennzahl, mit der Banken die F\u00e4higkeit einer Mietimmobilie zur Deckung des Schuldendienstes bewerten:</p><p><strong>DSCR = Nettomieteinnahmen / J\u00e4hrlicher Schuldendienst</strong></p><ul><li>Eine DSCR \u00fcber <strong>1,20</strong> wird von luxemburgischen Banken f\u00fcr einen Immobilienanlagekredit in der Regel gefordert.</li><li>Eine DSCR von <strong>1,00</strong> bedeutet, dass die Mieten die R\u00fcckzahlungen genau decken \u2014 eine riskante Situation bei Leerstand oder Unvorhergesehenem.</li><li>Eine DSCR unter <strong>1,00</strong> bedeutet, dass der Investor den Schuldendienst aus pers\u00f6nlichem Einkommen erg\u00e4nzen muss.</li></ul><p>F\u00fcr die Berechnung ber\u00fccksichtigt das Nettoeinkommen eine normative Leerstandsquote (in der Regel 5 bis 8 %), nicht umlagef\u00e4hige Nebenkosten und eine Instandhaltungsr\u00fccklage. Der Schuldendienst umfasst Zinsen und Tilgung.</p>",
  "faq1Q": "Festzins oder variabler Zins: Was w\u00e4hlen in Luxemburg?",
  "faq1A": "Die Wahl h\u00e4ngt von Ihrem Risikoprofil und Zeithorizont ab. Der Festzins bietet die Sicherheit einer konstanten Monatsrate, empfehlenswert bei maximaler Kreditaussch\u00f6pfung. Ein variabler Zins (EURIBOR + Marge) kann vorteilhafter sein, wenn die Zinsen sinken, setzt Sie aber Erh\u00f6hungen aus. In Luxemburg ist der gecappte variable Zins beliebt, der einen variablen Zins mit einer Obergrenze kombiniert. 2025 hat sich der Abstand zwischen fest und variabel verringert, was den Festzins besonders attraktiv macht.",
  "faq2Q": "Welches Eigenkapital braucht man mindestens f\u00fcr einen Kauf in Luxemburg?",
  "faq2A": "F\u00fcr Erstk\u00e4ufer (Hauptwohnsitz) ist eine 100-%-Finanzierung dank Staatsgarantie theoretisch m\u00f6glich. In der Praxis empfehlen die Banken ein Eigenkapital von 10 bis 20 %. F\u00fcr eine Kapitalanlage betr\u00e4gt das Mindesteigenkapital 20 % (LTV 80 %). Die Erwerbsnebenkosten (Registrierungsgeb\u00fchren, Notar, MwSt.) belaufen sich auf etwa 7 bis 10 % des Preises und werden in der Regel nicht finanziert \u2014 sie m\u00fcssen zum Eigenkapital hinzugerechnet werden.",
  "faq3Q": "Wie funktioniert die luxemburgische Staatsgarantie?",
  "faq3A": "Die staatliche Wohnungsgarantie (ge\u00e4ndertes Gesetz vom 25. Februar 1979) erm\u00f6glicht Erstk\u00e4ufern eine \u00f6ffentliche Garantie von bis zu 30 % des Darlehensbetrags, begrenzt auf 250.000 EUR. Diese Garantie erleichtert die Kreditaufnahme ohne Eigenkapital. Voraussetzungen sind eine Einkommensobergrenze des Haushalts und die Pflicht, die Immobilie als Hauptwohnsitz zu nutzen. Der Antrag wird beim Wohnungsbauministerium \u00fcber myguichet.lu gestellt.",
  "faq4Q": "Welchen Einfluss hat die CPE-Energieklasse auf den Kredit?",
  "faq4A": "Nach den CSSF-Empfehlungen zu Klimarisiken integrieren luxemburgische Banken schrittweise die Energieeffizienz in ihre Vergabekriterien. Eine Immobilie mit Klasse A-B kann von Vorzugskonditionen profitieren (Zinsreduktion von 10 bis 30 Bps). Umgekehrt werden Immobilien der Klassen F-G (Energieschleudern) verst\u00e4rkt gepr\u00fcft, teilweise mit Abschlag auf den Sch\u00e4tzwert und R\u00fcckstellung f\u00fcr energetische Sanierungskosten.",
  "faq5Q": "Kann man einen Immobilienkredit in Luxemburg umschulden?",
  "faq5A": "Ja, eine Umschuldung ist m\u00f6glich und kann vorteilhaft sein, wenn die Zinsen seit Vertragsabschluss gesunken sind. Zu erwartende Kosten: Vorf\u00e4lligkeitsentsch\u00e4digung (begrenzt auf 6 Monatszinsen oder 1 % des zur\u00fcckgezahlten Kapitals), Kosten f\u00fcr die L\u00f6schung der Hypothek (ca. 500 bis 1.000 EUR) und Kosten f\u00fcr die neue Hypothekeneintragung. Die Rentabilit\u00e4t h\u00e4ngt von der Zinsdifferenz, der Restschuld und der Restlaufzeit ab."
};

files.pt.outilsBancaires.seo = {
  "faqTitle": "Perguntas frequentes sobre cr\u00e9dito imobili\u00e1rio no Luxemburgo",
  "relatedTitle": "Ferramentas complementares",
  "creditTitle": "Ferramentas de cr\u00e9dito imobili\u00e1rio para o Luxemburgo",
  "creditContent": "<p>O mercado de cr\u00e9dito imobili\u00e1rio luxemburgu\u00eas apresenta especificidades importantes em rela\u00e7\u00e3o aos pa\u00edses vizinhos. O setor banc\u00e1rio \u00e9 dominado por atores locais (Spuerkeess/BCEE, BIL, BGL BNP Paribas, Raiffeisen) e bancos internacionais (ING, Deutsche Bank) que oferecem condi\u00e7\u00f5es diferenciadas.</p><p>As taxas de juro no Luxemburgo seguem as decis\u00f5es do <strong>Banco Central Europeu (BCE)</strong>, com um spread banc\u00e1rio t\u00edpico de 80 a 150 pontos base acima da taxa de refinanciamento. Em 2025, as taxas fixas a 10 anos situam-se entre 3,0 e 3,8%, enquanto as taxas vari\u00e1veis (indexadas ao EURIBOR a 3 meses) oscilam entre 3,2 e 4,0%.</p><p>A <strong>CSSF</strong> regulamenta as pr\u00e1ticas de concess\u00e3o atrav\u00e9s das suas circulares e recomenda\u00e7\u00f5es, nomeadamente em mat\u00e9ria de r\u00e1cio LTV (Loan-to-Value) e de capacidade de reembolso. Desde 2020, o Comit\u00e9 de Risco Sist\u00e9mico (CRS) emitiu recomenda\u00e7\u00f5es macroprudenciais espec\u00edficas para o mercado luxemburgu\u00eas.</p>",
  "ltvTitle": "R\u00e1cio LTV e limites CSSF",
  "ltvContent": "<p>O <strong>r\u00e1cio Loan-to-Value (LTV)</strong> \u00e9 a rela\u00e7\u00e3o entre o montante do empr\u00e9stimo e o valor do im\u00f3vel. A CSSF e o CRS emitiram recomenda\u00e7\u00f5es de limites m\u00e1ximos de LTV diferenciados:</p><ul><li><strong>Primeiros compradores (resid\u00eancia principal)</strong>: LTV m\u00e1ximo recomendado de 100% (financiamento integral poss\u00edvel sob condi\u00e7\u00f5es). Na pr\u00e1tica, os bancos concedem frequentemente LTVs de 90 a 100% aos primeiros compradores com garantia do Estado.</li><li><strong>Compradores n\u00e3o primeiros (resid\u00eancia principal)</strong>: LTV m\u00e1ximo recomendado de 90%, ou seja, 10% de entrada.</li><li><strong>Investimento para arrendamento</strong>: LTV limitado a 80%, exigindo uma entrada m\u00ednima de 20%. Alguns bancos s\u00e3o mais restritivos (75%).</li><li><strong>Buy-to-let</strong>: condi\u00e7\u00f5es espec\u00edficas aplicam-se, por vezes com limites de LTV a 70% e premia de taxa de 20 a 50 bps.</li></ul><p>\u00c9 importante notar que o LTV \u00e9 calculado sobre o <strong>valor de avalia\u00e7\u00e3o</strong> do im\u00f3vel, n\u00e3o sobre o pre\u00e7o de compra. Se o pre\u00e7o de compra exceder a avalia\u00e7\u00e3o, o banco utilizar\u00e1 o valor mais baixo.</p>",
  "capaciteTitle": "Capacidade de empr\u00e9stimo e a regra dos 40%",
  "capaciteContent": "<p>A capacidade de empr\u00e9stimo \u00e9 determinada pelo <strong>r\u00e1cio de endividamento</strong> (debt-to-income), que n\u00e3o deve geralmente exceder <strong>40% dos rendimentos l\u00edquidos</strong> do agregado familiar no Luxemburgo. Este limite \u00e9 mais generoso do que em alguns pa\u00edses vizinhos (35% em Fran\u00e7a, 33% na B\u00e9lgica).</p><ul><li><strong>Rendimentos considerados</strong>: sal\u00e1rio l\u00edquido, rendimentos de arrendamento (geralmente retidos a 70-80%), rendimentos de atividade independente (m\u00e9dia de 3 anos), pens\u00f5es.</li><li><strong>Encargos deduzidos</strong>: cr\u00e9ditos em curso, pens\u00f5es de alimentos, renda residual se aplic\u00e1vel.</li><li><strong>Rendimento residual</strong>: para al\u00e9m do r\u00e1cio de endividamento, os bancos luxemburgueses verificam um limiar m\u00ednimo de rendimento residual (aproximadamente 1.200 EUR/m\u00eas para solteiros, 2.000 EUR para casais).</li></ul><p>O nosso simulador calcula a presta\u00e7\u00e3o mensal m\u00e1xima admiss\u00edvel e deduz o montante m\u00e1ximo de empr\u00e9stimo.</p>",
  "amortissementTitle": "Amortiza\u00e7\u00e3o: constante vs. progressiva",
  "amortissementContent": "<p>Os bancos luxemburgueses oferecem principalmente dois tipos de amortiza\u00e7\u00e3o:</p><ul><li><strong>Amortiza\u00e7\u00e3o constante (anuidades fixas)</strong>: a presta\u00e7\u00e3o mensal permanece fixa durante todo o prazo do empr\u00e9stimo. A componente de juros diminui progressivamente enquanto a componente de capital aumenta. \u00c9 o esquema mais comum no Luxemburgo.</li><li><strong>Amortiza\u00e7\u00e3o linear (capital constante)</strong>: o reembolso de capital \u00e9 id\u00eantico em cada m\u00eas, produzindo presta\u00e7\u00f5es decrescentes. Os juros diminuem regularmente. Este esquema \u00e9 mais vantajoso em custo total de juros mas exige presta\u00e7\u00f5es iniciais mais elevadas.</li><li><strong>Bullet (s\u00f3 juros)</strong>: apenas os juros s\u00e3o pagos durante o prazo, com o capital reembolsado integralmente no vencimento. Utilizado principalmente para investimento locativo com seguro de vida como garantia.</li></ul><p>A nossa tabela de amortiza\u00e7\u00e3o detalha m\u00eas a m\u00eas a evolu\u00e7\u00e3o do capital em d\u00edvida, a reparti\u00e7\u00e3o juros/capital e o custo total do cr\u00e9dito.</p>",
  "dscrTitle": "DSCR para investimento locativo",
  "dscrContent": "<p>O <strong>Debt Service Coverage Ratio (DSCR)</strong> \u00e9 um r\u00e1cio utilizado pelos bancos para avaliar a capacidade de um im\u00f3vel arrendado cobrir o servi\u00e7o da d\u00edvida:</p><p><strong>DSCR = Rendimento L\u00edquido de Explora\u00e7\u00e3o / Servi\u00e7o Anual da D\u00edvida</strong></p><ul><li>Um DSCR superior a <strong>1,20</strong> \u00e9 geralmente exigido pelos bancos luxemburgueses para um cr\u00e9dito imobili\u00e1rio locativo.</li><li>Um DSCR de <strong>1,00</strong> significa que as rendas cobrem exatamente os reembolsos \u2014 situa\u00e7\u00e3o arriscada em caso de vac\u00e2ncia ou imprevisto.</li><li>Um DSCR inferior a <strong>1,00</strong> implica que o investidor deve complementar o servi\u00e7o da d\u00edvida com rendimentos pessoais.</li></ul><p>Para o c\u00e1lculo, o rendimento l\u00edquido integra uma vac\u00e2ncia normativa (geralmente 5 a 8%), encargos n\u00e3o recuper\u00e1veis e uma provis\u00e3o para obras. O servi\u00e7o da d\u00edvida compreende juros e reembolso de capital.</p>",
  "faq1Q": "Taxa fixa ou vari\u00e1vel: qual escolher no Luxemburgo?",
  "faq1A": "A escolha depende do seu perfil de risco e horizonte temporal. A taxa fixa oferece a seguran\u00e7a de uma presta\u00e7\u00e3o constante, recomendada se est\u00e1 a contrair cr\u00e9dito no m\u00e1ximo da sua capacidade. A taxa vari\u00e1vel (EURIBOR + margem) pode ser mais vantajosa se as taxas descerem, mas exp\u00f5e-no a subidas. No Luxemburgo, uma op\u00e7\u00e3o popular \u00e9 a taxa vari\u00e1vel com cap, que combina taxa vari\u00e1vel com um teto. Em 2025, o diferencial entre fixa e vari\u00e1vel reduziu-se, tornando a taxa fixa particularmente atrativa.",
  "faq2Q": "Qual a entrada m\u00ednima para comprar no Luxemburgo?",
  "faq2A": "Para primeiros compradores (resid\u00eancia principal), um financiamento a 100% \u00e9 teoricamente poss\u00edvel gra\u00e7as \u00e0 garantia do Estado. Na pr\u00e1tica, os bancos recomendam uma entrada de 10 a 20%. Para investimento locativo, a entrada m\u00ednima \u00e9 de 20% (LTV 80%). Os custos de aquisi\u00e7\u00e3o (direitos de registo, not\u00e1rio, IVA) representam cerca de 7 a 10% do pre\u00e7o e n\u00e3o s\u00e3o geralmente financiados \u2014 devem ser adicionados \u00e0 entrada.",
  "faq3Q": "Como funciona a garantia do Estado luxemburgu\u00eas?",
  "faq3A": "A garantia do Estado para habita\u00e7\u00e3o (lei alterada de 25 de fevereiro de 1979) permite aos primeiros compradores beneficiar de uma garantia p\u00fablica cobrindo at\u00e9 30% do montante do empr\u00e9stimo, limitada a 250.000 EUR. Esta garantia facilita a obten\u00e7\u00e3o de cr\u00e9dito sem entrada pessoal. As condi\u00e7\u00f5es incluem um teto de rendimentos do agregado familiar e a obriga\u00e7\u00e3o de habitar o im\u00f3vel como resid\u00eancia principal. O pedido \u00e9 feito ao Minist\u00e9rio da Habita\u00e7\u00e3o atrav\u00e9s do portal myguichet.lu.",
  "faq4Q": "Qual o impacto da classe energ\u00e9tica CPE no cr\u00e9dito?",
  "faq4A": "Ap\u00f3s as recomenda\u00e7\u00f5es da CSSF sobre riscos clim\u00e1ticos, os bancos luxemburgueses est\u00e3o a integrar progressivamente o desempenho energ\u00e9tico nos seus crit\u00e9rios de concess\u00e3o. Um im\u00f3vel classificado A-B pode beneficiar de condi\u00e7\u00f5es preferenciais (redu\u00e7\u00e3o de taxa de 10 a 30 bps). Inversamente, os im\u00f3veis classificados F-G (peneiras energ\u00e9ticas) s\u00e3o objeto de an\u00e1lise refor\u00e7ada, por vezes com desconto na avalia\u00e7\u00e3o e provisionamento dos custos de renova\u00e7\u00e3o energ\u00e9tica.",
  "faq5Q": "\u00c9 poss\u00edvel refinanciar um cr\u00e9dito imobili\u00e1rio no Luxemburgo?",
  "faq5A": "Sim, o refinanciamento \u00e9 poss\u00edvel e pode ser vantajoso se as taxas baixaram desde a contrata\u00e7\u00e3o. Custos a prever: indemniza\u00e7\u00e3o de reembolso antecipado (limitada a 6 meses de juros ou 1% do capital reembolsado), custos de cancelamento de hipoteca (cerca de 500 a 1.000 EUR) e custos de nova inscri\u00e7\u00e3o hipotec\u00e1ria. O c\u00e1lculo de rentabilidade depende do diferencial de taxas, do capital em d\u00edvida e da dura\u00e7\u00e3o residual."
};

files.lb.outilsBancaires.seo = {
  "faqTitle": "Heefeg Froen zum Immobiliekredit zu L\u00ebtzebuerg",
  "relatedTitle": "Erg\u00e4nzend Tools",
  "creditTitle": "Immobiliekredit-Tools fir L\u00ebtzebuerg",
  "creditContent": "<p>De l\u00ebtzebuergsche Immobiliekreditmaart huet bedeitend Besonneschkeeten am Verglach zu den Nopeschl\u00e4nner. De Bankesekteur g\u00ebtt vun lokalen Akteuren (Spuerkeess/BCEE, BIL, BGL BNP Paribas, Raiffeisen) an internationale Banken (ING, Deutsche Bank) dominéiert, d\u00e9i \u00ebnnerschiddlech Konditiounen ubidden.</p><p>D'Z\u00ebnss\u00e4tz zu L\u00ebtzebuerg follegen den Decisiounen vun der <strong>Europ\u00e4escher Zentralbank (EZB)</strong>, mat engem typeschen Bankenspread vu 80 bis 150 Basispunkten iwwer dem Refinanz\u00e9ierungstaux. Am Joer 2025 leien d'10-j\u00e4reg Festz\u00ebnse bei ronn 3,0 bis 3,8 %, w\u00e4hrend variabel Z\u00ebnse (index\u00e9iert op den 3-M\u00e9int-EURIBOR) t\u00ebschent 3,2 an 4,0 % schwanken.</p><p>D'<strong>CSSF</strong> reguléiert d'Vergabepraxis iwwer hir Rundschreiwen an Empfehlungen, besonnesch wat den LTV-Verh\u00e4ltnis an d'R\u00e9ckzuelungsf\u00e4hegkeet ug\u00ebt.</p>",
  "ltvTitle": "LTV-Verh\u00e4ltnis a CSSF-Schwellewäerter",
  "ltvContent": "<p>D'<strong>Loan-to-Value-Verh\u00e4ltnis (LTV)</strong> ass d'Verh\u00e4ltnis t\u00ebschent dem Darlehensb\u00e9trag an dem Immobilienw\u00e4ert. D'CSSF an de CRS hunn differenz\u00e9iert LTV-Uewergrenzen empfohlen:</p><ul><li><strong>\u00c9ischtkeeferinnen (Haaptwunnsitz)</strong>: empfohlene maximalen LTV vun 100 % (Vollfinanz\u00e9ierung \u00ebnner Bedingunge m\u00e9iglech).</li><li><strong>Net-\u00c9ischtkeeferinnen (Haaptwunnsitz)</strong>: empfohlene maximalen LTV vun 90 %, also 10 % Eegekaptial.</li><li><strong>Kapitalanlag</strong>: LTV begrenzt op 80 %, mindestens 20 % Eegekaptial n\u00e9ideg.</li><li><strong>Buy-to-let</strong>: besonnesch Bedingunge gëllen, deelweis mat 70 % LTV-Schwellen.</li></ul><p>Wichteg: Den LTV g\u00ebtt op Basis vum <strong>Sch\u00e4tzw\u00e4ert</strong> vun der Immobilie berechent, net vum Kafspr\u00e4is.</p>",
  "capaciteTitle": "Kreditkapazit\u00e9it an d'40-%-Reegel",
  "capaciteContent": "<p>D'Kreditkapazit\u00e9it g\u00ebtt duerch d'<strong>Schold end\u00e9ngschtquot</strong> bestëmmt, d\u00e9i zu L\u00ebtzebuerg normalerweis <strong>40 % vum Nettoak ommes</strong> vum M\u00e9nage net iwwerschr\u00e4ide soll. D\u00ebse Schwellew\u00e4ert ass m\u00e9i generéis wéi an e puer Nopeschl\u00e4nner (35 % a Frankräich, 33 % a Belsch).</p><ul><li><strong>Ber\u00fccksichtegt Akommes</strong>: Nettogehalt, Mieteinnahmen (normalerweis zu 70-80 % ugerechent), Akommes aus selbstst\u00e4nneger T\u00e4tegkeet, Pensiounen.</li><li><strong>Ofgezunn Belaaschtungen</strong>: laafen Kreditter, Ënnerhaltszuelungen.</li><li><strong>Verbleiwend Akommes</strong>: L\u00ebtzebuergsch Banken pr\u00e9iwen en Mindest-Restakommes (ca. 1.200 EUR/Mount fir Eenzelp\u00e9iersounen, 2.000 EUR fir Koppelen).</li></ul>",
  "amortissementTitle": "Tilgung: konstant vs. progressiv",
  "amortissementContent": "<p>L\u00ebtzebuergsch Banke bidden haaptsächlech zwou Tilgungsaarten un:</p><ul><li><strong>Konstant Tilgung (fest Annuit\u00e9iten)</strong>: D'Monatsrat bleift w\u00e4hrend der ganzer Laufzäit gl\u00e4ich. Den Z\u00ebnsdeel s\u00ebnkt progressiv, w\u00e4hrend den Tilgungsdeel klammt.</li><li><strong>Linear Tilgung (konstante Kapitalb\u00e9trag)</strong>: D'Kapitalr\u00e9ckzuelung ass all Mount gl\u00e4ich, wat zu sinkende Monatsrate f\u00e9iert.</li><li><strong>Endf\u00e4lleg (tilgungsfr\u00e4i)</strong>: W\u00e4hrend der Laafz\u00e4it gi just Z\u00ebnsen bezuelt, d'Kapital g\u00ebtt um Enn an enger Somm zeréckbezuelt.</li></ul>",
  "dscrTitle": "DSCR fir Kapitalanlagimmobilien",
  "dscrContent": "<p>D'<strong>Debt Service Coverage Ratio (DSCR)</strong> ass eng Kennzuel, mat d\u00e4r Banken d'F\u00e4hegkeet vun enger Mietimmobilie zur Deckung vum Scholdend\u00e9ngscht bewäerten:</p><p><strong>DSCR = Nettomieteinnahmen / J\u00e4hrleche Scholdend\u00e9ngscht</strong></p><ul><li>Eng DSCR iwwer <strong>1,20</strong> g\u00ebtt vu l\u00ebtzebuergsche Banken normalerweis gefuerdert.</li><li>Eng DSCR vun <strong>1,00</strong> bed\u00e4it, datt d'Mie ten d'R\u00e9ckzuelungen genee decken \u2014 eng riskant Situatioun.</li><li>Eng DSCR \u00ebnner <strong>1,00</strong> bed\u00e4it, datt den Investisseur de Scholdend\u00e9ngscht aus pers\u00e9inlechem Akommes erg\u00e4nze muss.</li></ul>",
  "faq1Q": "Festz\u00ebns oder variabelen Z\u00ebns: Wat wielen zu L\u00ebtzebuerg?",
  "faq1A": "D'Wiel h\u00e4nkt vun \u00c4rem Risikoprofil an Z\u00e4ithorizont of. De Festz\u00ebns bitt d'S\u00e9cherheet vun enger konstanter Monatsrat. En variabelen Z\u00ebns (EURIBOR + Marge) kann m\u00e9i virdeel haft sinn wann d'Z\u00ebnsen s\u00ebnken. Zu L\u00ebtzebuerg ass de gecappte variabelen Z\u00ebns bel\u00e9iwt. 2025 huet sech den Ofstand t\u00ebschent fest a variabel verréngert.",
  "faq2Q": "W\u00e9ivill Eegekaptial brauch ee mindestens fir en Kaf zu L\u00ebtzebuerg?",
  "faq2A": "Fir \u00c9ischtkeeferinnen (Haaptwunnsitz) ass eng 100-%-Finanz\u00e9ierung duerch d'Staatsgarantie theoreetesch m\u00e9iglech. An der Praxis empfeelen d'Banke 10 bis 20 % Eegekaptial. Fir eng Kapitalanlag betr\u00e9it d'Mindest-Eegekaptial 20 % (LTV 80 %). D'Erwerbsniewekäschten (Registr\u00e9ierungs geb\u00e9ieren, Notaire, MwSt.) belaafe sech op ronn 7 bis 10 % vum Pr\u00e4is.",
  "faq3Q": "W\u00e9i fonctionn\u00e9iert d'l\u00ebtzebuergsch Staatsgarantie?",
  "faq3A": "D'statlech Wunngarantie (ge\u00e4nnert Gesetz vum 25. Februar 1979) erlaabt \u00c9ischtkeeferinnen eng \u00ebffentlech Garantie vu bis zu 30 % vum Darlehensb\u00e9trag, begrenzt op 250.000 EUR. D\u00ebs Garantie erliichtert d'Kreditopnam ouni Eegekaptial.",
  "faq4Q": "W\u00e9i en Afloss huet d'CPE-Energieklass op de Kredit?",
  "faq4A": "No den CSSF-Empfehlungen zu Klimarisiken int\u00e9gr\u00e9ieren l\u00ebtzebuergsch Banke schr\u00ebttweis d'Energieeffizienz an hir Vergabekrit\u00e4ren. Eng Immobilie mat Klass A-B kann vu Virdeel skonditiounen profitéieren. \u00cbmgekéiert ginn Immobilien vun de Klassen F-G verst\u00e4erkt gepr\u00e9ift.",
  "faq5Q": "Kann een en Immobiliekredit zu L\u00ebtzebuerg \u00ebmschulden?",
  "faq5A": "Jo, eng \u00cbmschuldung ass m\u00e9iglech a kann virdeel haft sinn wann d'Z\u00ebnse gefall sinn. K\u00e4schten: Virf\u00e4llegkeetsent sch\u00e4degung (begrenzt op 6 Monatsz\u00ebnsen oder 1 % vum zr\u00e9ckbezueltem Kapital), K\u00e4schte fir d'L\u00e4schung vun der Hypo th\u00e9ik an K\u00e4schte fir d'nei Hypothéikeregistr\u00e9ierung."
};

// Save
for (const lang of langs) {
  fs.writeFileSync(`C:/tevaxia/src/messages/${lang}.json`, JSON.stringify(files[lang], null, 2) + '\n', 'utf8');
}
console.log('outilsBancaires.seo done');
