#!/usr/bin/env python3
"""Generate the list of message namespaces used by client components.

Output: src/i18n/client-namespaces.ts (auto-generated, DO NOT EDIT)
Used by the root layout to pick only client-needed messages, drastically
reducing the HTML payload size shipped to browsers (avoids Bing's "html
size > 1 MB" warning).

Run before build (also wired into npm script).
"""
import re
from pathlib import Path

ROOT = Path(__file__).parent.parent
SRC = ROOT / "src"
OUT = SRC / "i18n" / "client-namespaces.ts"


def collect_client_namespaces() -> list[str]:
    namespaces: set[str] = set()
    # Pass 1: literal useTranslations("ns") in client components
    for f in SRC.rglob("*.tsx"):
        try:
            text = f.read_text(encoding="utf-8")
        except UnicodeDecodeError:
            continue
        if '"use client"' not in text:
            continue
        for m in re.findall(r"useTranslations\(\s*['\"]([^'\"]+)['\"]", text):
            namespaces.add(m.split(".")[0])

    # Pass 2: <SEOContent ns="..."> — SEOContent is a client component that
    # builds namespaces dynamically as `${ns}.seo`. Page is a server component
    # but the resolved ns must reach the client provider.
    for f in SRC.rglob("*.tsx"):
        try:
            text = f.read_text(encoding="utf-8")
        except UnicodeDecodeError:
            continue
        for m in re.findall(r"<SEOContent[^>]*\sns=\"([^\"]+)\"", text):
            namespaces.add(m.split(".")[0])

    # Pass 3: <ModuleContextBar moduleKey="..."> dispatches to a hardcoded
    # set of namespaces (syndicContextBar, pmsContextBar, crmContextBar,
    # hotellerieContextBar). Add them explicitly.
    namespaces.update({
        "syndicContextBar", "pmsContextBar", "crmContextBar", "hotellerieContextBar",
    })

    return sorted(namespaces)


def main() -> None:
    names = collect_client_namespaces()
    body = "// AUTO-GENERATED by scripts/generate_client_namespaces.py — DO NOT EDIT\n"
    body += "// Run `npm run build` (or `python scripts/generate_client_namespaces.py`) to regenerate.\n\n"
    body += "export const CLIENT_NAMESPACES = [\n"
    for n in names:
        body += f'  "{n}",\n'
    body += "] as const;\n"
    OUT.parent.mkdir(parents=True, exist_ok=True)
    OUT.write_text(body, encoding="utf-8")
    print(f"Wrote {len(names)} namespaces to {OUT}")


if __name__ == "__main__":
    main()
